### ISSUE TITLE
Feature request: ley D'Hondt

### ISSUE THREAD

**Issue by manmacbec** [decide-europa-postproc/Decide_Europa_Postproc#1]
**Describe the solution you'd like**
El sistema debe contener una implementación del sistema D'Hondt para las votaciones que lo permitan.

**Additional context**
El sistema D'Hondt es un método para la asignación de escaños. Este sistema intenta asignarlos de manera proporcional al número de votos recibidos puesto que, generalmente, no es posible la proporcionalidad exacta.

**Comment by pabgarbar** [comment]
Probado el método de la Ley D'hondt, todo correcto para hacer merge.

**Comment by albertopumar** [comment]
El método de la Ley D`hondt funciona como esperado. Queda aprobado para unir la funcionalidad al master.
