### ISSUE TITLE
Feature request: Mejora de la gestión de incidencias-código

### ISSUE THREAD

**Issue by albertopumar** [decide-europa-postproc/Decide_Europa_Postproc#10]
**Is your feature request related to a problem? Please describe.**
Actualmente para validar una nueva feature necesitamos que todo el equipo que no ha estado trabajando en ella la valide. Esto es un gasto inecesario de tiempo.

**Describe the solution you'd like**
Utilizaremos las tecnicas que nos proveen git y github para hacer una mejor gestión tanto de las incidencias como del código.

**Comment by pabgarbar** [comment]
Todos los test pasados y todo en orden.
