### ISSUE TITLE
Feature request: método de Sainte-Laguë

### ISSUE THREAD

**Issue by manmacbec** [decide-europa-postproc/Decide_Europa_Postproc#2]
**Describe the solution you'd like**
El sistema debe contener una implementación del sistema Sainte-Laguë para las votaciones que lo permitan.

**Additional context**
Este método consiste en realizar una asignación de escaños basados en unos cocientes sucesivos propios para cada lista electoral.

**Comment by javcasdel** [comment]
Funciona correctamente, está listo para añadirlo al master.

**Comment by manmacbec** [comment]
Comprobado su funcionamiento ya se puede añadir a master.
