### ISSUE TITLE
Feature request: refactorización de código anterior

### ISSUE THREAD

**Issue by manmacbec** [decide-europa-postproc/Decide_Europa_Postproc#3]
**Describe the solution you'd like**
Reescribir el código anterior para mejorar el rendimiento del sistema y la legibilidad. Importante que los datos de los tests tengan un formato que permita copiar y pegar en la url _/postproc_ (JSON).

**Additional context**
Se pretende reescribir el código aportado por wadobo, valorando la consistencia con el código de los nuevos desarrolladores.

**Comment by manmacbec** [comment]
Funcionalidad revisada, listo para el merge con el máster.

**Comment by albertopumar** [comment]
Revisado, listo para realizar el merge con el master.

**Comment by pabgarbar** [comment]
Todo revisado y listo para hacer merge con el máster.
