### ISSUE TITLE
Feature request: votaciones con paridad

### ISSUE THREAD

**Issue by manmacbec** [decide-europa-postproc/Decide_Europa_Postproc#4]
**Describe the solution you'd like**
El sistema debe contener una implementación de votaciones con paridad. Esto implica que cada una de las opciones tiene un número de votos y un número de grupo al que pertenecen. A la hora de hacer la asignación de escaños, se entienden los resultados como varias votaciones diferentes divididas en grupos, por lo que se le asigna una fracción de escaños correspondiente a cada uno.

**Additional context**
Se debe permitir la elección del método de recuento (d'Hondt o Sainte-Laguë).

**Comment by albertopumar** [comment]
Feature implementada correctamente

**Comment by pabgarbar** [comment]
Funciona correctamente y cumple con la funcionalidad requerida

**Comment by manmacbec** [comment]
Comprobada la funcionalidad se procede al merge con master.
