### ISSUE TITLE
Feature request: autogeneración de releases

### ISSUE THREAD

**Issue by manmacbec** [decide-europa-postproc/Decide_Europa_Postproc#6]
**Is your feature request related to a problem? Please describe.**
Es necesaria la autogeneración de releases al hacer push a la rama master para no tener que hacerlos manualmente con cualquier cambio de esta rama.

**Describe the solution you'd like**
Se pretende que las releases se hagan automáticamente mediante el uso de Travis CI al hacer push a la rama master.

**Comment by pabgarbar** [comment]
Funciona correctamente.

**Comment by albertopumar** [comment]
Comprobado, funciona correctamente.
