### ISSUE TITLE
Feature request: soporte multipregunta

### ISSUE THREAD

**Issue by albertopumar** [decide-europa-postproc/Decide_Europa_Postproc#7]
**Is your feature request related to a problem? Please describe.**
A la hora de realizar una encuesta en la que existan varias preguntas, se necesita un método que soporte respuestas a múltiples preguntas.

**Describe the solution you'd like**
Debemos poder recibir y tratar la información relacionada con una votación con varias preguntas procedente de la rama de recuento del proyecto.

**Additional context**
Esta feature es una integración coordinada con grupos ajenos al nuestro.

**Comment by pabgarbar** [comment]
Ya esta listo para unir con el master y testeado.

**Comment by manmacbec** [comment]
Se ha probado la funcionalidad y cumple con lo esperado.
